#!/bin/sh
# vim: set ft=sh ts=3 sts=3 sw=3 :
# utility functions

unkey-host()
{
   ssh-keygen -R "${1##*@}"
}

mkcd()
{
   if [ -d "${1}" ] ; then
      cd "${1}"
   else
      mkdir -p "${1}" && cd "${1}"
   fi
}

extract()
{
   if [ ! -f "${1}" ] ; then
      echo "The file '${1}' does not exist!" >&2
      return 1
   fi

   local filename=$(echo -- ${1} | tr '[:upper:]' '[:lower:]')

   case "${filename}" in
      *.tar)
         tar xf "${1}" --no-same-owner
      ;;
      *.tar.7z)
         7z x -y -so | tar xf - --no-same-owner
      ;;
      *.tar.bz2|*.tbz2)
         tar jxf "${1}" --no-same-owner
      ;;
      *.tar.gz|*.tgz)
         tar zxf "${1}" --no-same-owner
      ;;
      *.tar.lzma)
         lzma -dc "${1}" | tar xf - --no-same-owner
      ;;
      *.tar.xz)
         xz -dc "${1}" | tar xf - --no-same-owner
      ;;
      *.7z)
         7z x -y "${1}"
      ;;
      *.a|*.deb)
         ar x "${1}"
      ;;
      *.ace)
         unace x "${1}"
      ;;
      *.arj)
         arj x "${1}"
      ;;
      *.bz2)
         bzip2 -dc "${1}" > $(basename "${1%.*}")
      ;;
      *.cpio)
         cpio -id < "${1}"
      ;;
      *.gz|*.z)
         gzip -dc "${1}" > $(basename "${1%.*}")
      ;;
      *.jar|*.zip)
         unzip -qo "${1}"
      ;;
      *.lha)
         lha xfq "${1}"
      ;;
      *.lzma)
         lzma -dc "${1}" > $(basename "${1%.*}")
      ;;
      *.pax)
         pax -rf "${1}"
      ;;
      *.rar)
         unrar x -idq "${1}"
      ;;
      *.rpm)
         rpm2cpio "${1}" | cpio -id
      ;;
      *.xz)
         xz -dc "${1}" > $(basename "${1%.*}")
      ;;
   esac
}

